
@baseUrl = http://127.0.0.1:8000

### Traeme la raiz del servidor para probarlo
GET {{baseUrl}}/


### Traeme un contacto por ID
GET {{baseUrl}}/contacto/4

### Buscar contactos por nombre o apellido
GET {{baseUrl}}/buscar/?texto=ana

### Agregar un nuevo contacto
POST {{baseUrl}}/agregar
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Jimenez",
    "email": "juan.jimenez@example.com"
}


### Listar todos los contactos
GET {{baseUrl}}/contactos/